import { GoogleGenAI, ThinkingLevel } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export async function getCelebrityBirthdate(celebrityName: string) {
  if (!celebrityName.trim()) {
    throw new Error("Celebrity name cannot be empty.");
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.1-pro-preview",
      contents: `Find the exact birth date and a public profile image URL of the celebrity: ${celebrityName}. 
      Return ONLY a JSON object with the following fields:
      {
        "name": "Full Name",
        "birthDate": "YYYY-MM-DD",
        "description": "Brief 1-sentence description",
        "category": "Actor, Scientist, Musician, etc.",
        "imageUrl": "A valid public URL to a photo of this person",
        "nationality": "Nationality",
        "knownFor": "What they are most famous for",
        "achievements": ["Achievement 1", "Achievement 2"]
      }
      If you cannot find a direct image URL, provide a high-quality placeholder URL from a service like Unsplash or similar that matches their category.`,
      config: {
        thinkingConfig: { thinkingLevel: ThinkingLevel.HIGH },
        responseMimeType: "application/json"
      },
    });

    if (!response.text) {
      throw new Error("Empty response from AI service.");
    }

    const data = JSON.parse(response.text);
    if (!data.name || !data.birthDate) {
      throw new Error("Incomplete data received from AI service.");
    }

    return data;
  } catch (error: any) {
    console.error("Error fetching celebrity data:", error);
    if (error.message?.includes("API key")) {
      throw new Error("AI service configuration error. Please check API settings.");
    }
    throw new Error(`Failed to find information for "${celebrityName}". Please try a different name.`);
  }
}

export async function getCelebritySuggestions(query: string) {
  if (!query.trim() || query.length < 2) {
    return [];
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Provide a list of 5 famous people whose names start with or contain "${query}". 
      Return ONLY a JSON array of strings.`,
      config: {
        responseMimeType: "application/json"
      },
    });

    if (!response.text) {
      return [];
    }

    const data = JSON.parse(response.text);
    if (Array.isArray(data)) {
      return data;
    }
    return [];
  } catch (error) {
    console.error("Error fetching suggestions:", error);
    return [];
  }
}

export async function generateAgeVisualization(ageDescription: string) {
  if (!ageDescription) {
    throw new Error("Age description is required for visualization.");
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `A conceptual, artistic visualization of time and age for someone who is ${ageDescription}. 
            The style should be modern, clean, and abstract, using soft gradients and geometric shapes. 
            No text in the image. High quality, 4k resolution.`,
          },
        ],
      },
    });

    const part = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
    if (part?.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
    
    throw new Error("No image data generated by AI service.");
  } catch (error: any) {
    console.error("Error generating image:", error);
    if (error.message?.includes("API key")) {
      throw new Error("AI service configuration error. Please check API settings.");
    }
    throw new Error("Failed to generate visualization. Please try again in a moment.");
  }
}
